services:
  - type: web
    name: remaleh-protect-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/main.py
    envVars:
      - key: DEBUG
        value: false
      - key: FLASK_ENV
        value: production
    healthCheckPath: /api/scam/health

